on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install uv
      - run: for slide in $(ls -d slides/*); do uvx mkslides build $slide --config-file $slide/mkslides.yml --site-dir ./site/slides/$slide; done
      - run: for tutorial in $(ls -d tutorials/*); do uvx python render.py pdf $tutorial; done
      - run: for thing in $(ls -d */*); do echo "<a href=\"$thing/index.html\">$thing</a><br>" >> ./site/index.html; done
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./site
      - id: deployment
        uses: actions/deploy-pages@v4
